name: AI Reviewer
description: Automatically review pull requests using OpenAI's GPT
branding:
    icon: git-pull-request
    color: gray-dark
inputs:
    OPENAI_API_KEY:
        description: 'API key for OpenAI'
        required: true
    GITHUB_TOKEN:
      description: 'Token for GitHub'
      required: true

runs:
  using: node20
  main: 'dist/index.js'
